import { Header } from '@/components/Header'
import { Sidebar } from '@/components/Sidebar'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import localFont from 'next/font/local'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})
const mont = Montserrat({
	subsets: ['latin'],
	variable: '--font-montserrat',
	weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
	title: 'Extense',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${mont.variable} antialiased`}
			>
				<NextTopLoader />
				<Toaster position='top-right' />
				<div className='flex'>
					<Sidebar />
					<div className='flex flex-col flex-grow xl:ml-56 2xl:ml-64 3xl:ml-80'>
						<Header />
						<main className='p-4'>{children}</main>
					</div>
				</div>
			</body>
		</html>
	)
}
